spring.config.activate.on-profile=docker

catalog.base-url=http://catalog-service:8081
services.user.base-url=http://user-service:8082
ia.base-url=http://pairing-ia-service:8084
admin.base-url=http://admin-service:8083
