spring.config.activate.on-profile=docker

# =============================
# MICROSERVICIOS - ENDPOINTS (DOCKER)
# =============================

# Dentro de docker usamos los nombres de servicio del docker-compose
catalog.base-url=http://catalog-service:8081/api/v1
services.user.base-url=http://user-service:8082
ia.base-url=http://ia-service:8083
